-- User widgets generated by the AI chat
CREATE TABLE IF NOT EXISTS user_widgets (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    html TEXT NOT NULL,
    permissions TEXT[] NOT NULL DEFAULT '{}',
    is_public BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_widgets_user_id ON user_widgets(user_id);
CREATE INDEX IF NOT EXISTS idx_user_widgets_public ON user_widgets(is_public) WHERE is_public = true;

ALTER TABLE user_widgets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own or public widgets" ON user_widgets
    FOR SELECT USING (auth.uid() = user_id OR is_public = true);

CREATE POLICY "Users can create their own widgets" ON user_widgets
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own widgets" ON user_widgets
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own widgets" ON user_widgets
    FOR DELETE USING (auth.uid() = user_id);

-- Per-user consent to widget permissions + "enabled in navigation panel" flag
CREATE TABLE IF NOT EXISTS widget_grants (
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    widget_id UUID NOT NULL REFERENCES user_widgets(id) ON DELETE CASCADE,
    permissions TEXT[] NOT NULL DEFAULT '{}',
    enabled BOOLEAN NOT NULL DEFAULT true,
    granted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (user_id, widget_id)
);

CREATE INDEX IF NOT EXISTS idx_widget_grants_user_enabled ON widget_grants(user_id) WHERE enabled = true;

ALTER TABLE widget_grants ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own widget grants" ON widget_grants
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own widget grants" ON widget_grants
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own widget grants" ON widget_grants
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own widget grants" ON widget_grants
    FOR DELETE USING (auth.uid() = user_id);

-- Per (widget, user) key-value state used by the widget.storage SDK API
CREATE TABLE IF NOT EXISTS widget_storage (
    widget_id UUID NOT NULL REFERENCES user_widgets(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    key VARCHAR(255) NOT NULL,
    value JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (widget_id, user_id, key)
);

ALTER TABLE widget_storage ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own widget storage" ON widget_storage
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own widget storage" ON widget_storage
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own widget storage" ON widget_storage
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own widget storage" ON widget_storage
    FOR DELETE USING (auth.uid() = user_id);

-- Keep updated_at fresh
CREATE OR REPLACE FUNCTION update_user_widgets_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_user_widgets_updated_at_trigger
    BEFORE UPDATE ON user_widgets
    FOR EACH ROW
    EXECUTE FUNCTION update_user_widgets_updated_at();

CREATE TRIGGER update_widget_storage_updated_at_trigger
    BEFORE UPDATE ON widget_storage
    FOR EACH ROW
    EXECUTE FUNCTION update_user_widgets_updated_at();
