"use client";

import {
  createMessageRendererRegistry,
  registerMessageRenderer,
} from "@gravity-ui/aikit";
import type { MessageContentComponentProps, TMessageContent } from "@gravity-ui/aikit";
import { ParsedWidgetBlock } from "@/features/widget-runtime/lib/parseWidgetBlock";
import { WidgetPreviewCard } from "@/features/widget-generation/ui/WidgetPreviewCard";
import { PendingMessageSkeleton, PendingMessageSkeletonData } from "./PendingMessageSkeleton";

// Custom aikit message parts: a widget generated by the assistant and the
// skeleton placeholder shown while a response is being generated
export type WidgetMessageContent = TMessageContent<'widget', ParsedWidgetBlock>;
export type PendingSkeletonContent = TMessageContent<'pending-skeleton', PendingMessageSkeletonData>;
export type CustomMessageContent = WidgetMessageContent | PendingSkeletonContent;

function WidgetMessagePart({ part }: MessageContentComponentProps<WidgetMessageContent>) {
  return <WidgetPreviewCard widget={part.data} />;
}

function PendingSkeletonPart({ part }: MessageContentComponentProps<PendingSkeletonContent>) {
  return <PendingMessageSkeleton variant={part.data.variant} />;
}

export const widgetMessageRegistry = registerMessageRenderer<PendingSkeletonContent>(
  registerMessageRenderer<WidgetMessageContent>(
    createMessageRendererRegistry(),
    'widget',
    { component: WidgetMessagePart }
  ),
  'pending-skeleton',
  { component: PendingSkeletonPart }
);
