"use client";

import {
  createMessageRendererRegistry,
  registerMessageRenderer,
} from "@gravity-ui/aikit";
import type { MessageContentComponentProps, TMessageContent } from "@gravity-ui/aikit";
import { ParsedWidgetBlock } from "@/features/widget-runtime/lib/parseWidgetBlock";
import { WidgetPreviewCard } from "@/features/widget-generation/ui/WidgetPreviewCard";

// Custom aikit message part: a widget generated by the assistant
export type WidgetMessageContent = TMessageContent<'widget', ParsedWidgetBlock>;

function WidgetMessagePart({ part }: MessageContentComponentProps<WidgetMessageContent>) {
  return <WidgetPreviewCard widget={part.data} />;
}

export const widgetMessageRegistry = registerMessageRenderer<WidgetMessageContent>(
  createMessageRendererRegistry(),
  'widget',
  { component: WidgetMessagePart }
);
